language: python
sudo: required


services:
  - docker

python:
  - "3.6"

branches:
  only:
    - master
    - develop

install:
  - pip install coverage coveralls

script:
  - sh -x run coverage
  - cd reports && coverage combine

after_success:
  cd reports && coveralls
