language: python
sudo: required


services:
  - postgresql
  - docker

python:
  - "2.7"

branches:
  only:
    - master
    - develop

install:
  - pip install -r radioco/configs/base/requirements.txt
  - pip install coverage coveralls invoke

script:
  - python manage.py test
  - COVERAGE_FILE=.coverage.base.xml coverage run --source="radioco" manage.py test
  - inv --echo docker.setup -e base
  - inv --echo docker.run_coverage -e base
  - inv --echo docker.destroy -e base
  - inv --echo docker.setup -e staging
  - inv --echo docker.run_coverage -e staging
  - inv --echo docker.destroy -e staging
  - inv --echo docker.setup -e development
  - inv --echo docker.run_coverage -e development
  - inv --echo docker.destroy -e development
  - coverage combine

after_success:
  coveralls
