language: python
sudo: false

services:
  - postgresql

python:
  - "2.7"

branches:
  only:
    - master
    - develop

install:
  - pip install -r radioco/configs/base/requirements.txt
  - pip install coverage coveralls

script:
  - python manage.py test
  - coverage run --source="radioco" manage.py test

after_success:
  coveralls
