language: python
sudo: required


services:
  - docker

python:
  - "2.7"

branches:
  only:
    - master
    - develop

install:
  - pip install coverage coveralls invoke

script:
  - inv --echo docker.setup -e base
  - inv --echo docker.run_coverage -e base
  - inv --echo docker.destroy -e base
  - coverage combine

after_success:
  coveralls
