language: python
sudo: required


services:
  - docker

python:
  - "3.6"

branches:
  only:
    - master
    - develop

install:
  - pip install coveralls

script:
  - cp -v .sample.env .env
  - docker-compose run -e COVERAGE_FILE=reports/coverage.xml --rm --volume "$(pwd)/reports:/radioco/reports" django coverage run manage.py test radioco

after_success:
  cd reports && coveralls
