version: '2'
services:


  # Backend server -------------------------------------------------------------

  django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    environment:
      - DJANGO_LOG_LEVEL=ERROR
      - MANAGE_PY
    volumes:
      - ./:/radioco
    expose:
      - ${PORT_BACKEND}
    ports:
      - ${PORT_BACKEND}:8000
    command: /radioco/docker/scripts/launch_server.sh
    stdin_open: true
    #tty: true  # ERROR: An HTTP request took too long to complete. https://github.com/docker/compose/issues/3633
