version: '2'
services:


  # Backend server -------------------------------------------------------------

  development_django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    links:
      - development_postgres
    volumes:
      - ../../../:/radioco
    env_file:
      - .env
    ports:
      - "${PORT_BACKEND}:8000"
      - "${PORT_SSHD}:22"
    command: /radioco/radioco/configs/${ENVIRONMENT}/docker/scripts/launch_sshd.sh
    stdin_open: true


  # Datastore Containers -------------------------------------------------------
  
  development_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - .env
    volumes:
      - data_development_postgres:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "${PORT_POSTGRES}:5432"

volumes:
    data_development_postgres:
