version: '2'
services:


  # Backend server -------------------------------------------------------------

  staging_django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    links:
      - staging_postgres
    volumes:
      - ../../../:/radioco
    env_file:
      - .env
    expose:
      - ${PORT_BACKEND}
    command: /bin/sh -c "cd /radioco && gunicorn radioco.configs.staging.wsgi -b 0.0.0.0:${PORT_BACKEND}"

  staging_nginx:
    image: nginx:1.11-alpine
    restart: always
    ports:
      - "${PORT_NGINX}:80"
    volumes:
      - ./docker/nginx.conf:/tmp/nginx.conf:ro
      - ../../static:/static:ro
      - ../../media:/media:ro
    env_file:
      - .env
    command: /bin/sh -c "envsubst '$$PORT_NGINX $$PORT_BACKEND' < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    links:
      - staging_django


  # Datastore Containers -------------------------------------------------------
  
  staging_postgres:
    image: postgres:9.6
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - data_staging_postgres:/var/lib/postgresql/data
    expose:
      - 5432


volumes:
    data_staging_postgres:
